name:                morph-dawg
version:             0.1.0.0
github:              "eugeneai/morph-dawg"
license:             BSD-3-Clause
author:              "Evgeny Cherkashin"
maintainer:          "eugeneai@irnok.net"
copyright:           "2024 Evgeny Cherkashin"
spec-version:        0.36.0

extra-source-files:
- README.md
- CHANGELOG.md
- src/Morphy/*.h
- lib/b64/*
- lib/dawgdic/*
- lib/AUTHORS
- lib/COPYING
- lib/*.cc

extra-lib-dirs:
- /home/eugeneai/projects/code/haskell/morph-dawg/src/Morphy


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/morph-dawg#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 2.0.0 && < 3
- base-compat
- containers
- bytestring
- utf8-string
- with-utf8
- bytestring
- byteslice
- split
- base64
- vector
- array
- binary

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Morphy
    - Morphy.DAWG
    - Morphy.DAWGDict
    - Morphy.Paradigm
  cxx-sources:
    - src/Morphy/*.cc
  cxx-options:
    - -std=c++17

include-dirs:
    - lib

data-files:
    - corpora/**/*

extra-libraries:
    - stdc++

executables:
  morph-dawg-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - morph-dawg

tests:
  morph-dawg-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - morph-dawg
